config/routes.rb
  match 'api/0.6/relation/:id/relations' => 'relation#relations_for_relation', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id/history' => 'old_relation#history', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id/full' => 'relation#full', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id/:version/redact' => 'old_relation#redact', :via => :post, :version => /\d+/, :id => /\d+/
  match 'api/0.6/relation/:id/:version' => 'old_relation#version', :via => :get, :id => /\d+/, :version => /\d+/
  match 'api/0.6/relation/:id' => 'relation#read', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id' => 'relation#update', :via => :put, :id => /\d+/
  match 'api/0.6/relation/:id' => 'relation#delete', :via => :delete, :id => /\d+/
  match 'api/0.6/relations' => 'relation#relations', :via => :get

  match 'api/0.6/map' => 'api#map', :via => :get

  match 'api/0.6/trackpoints' => 'api#trackpoints', :via => :get

  match 'api/0.6/changes' => 'api#changes', :via => :get

  match 'api/0.6/search' => 'search#search_all', :via => :get
  match 'api/0.6/ways/search' => 'search#search_ways', :via => :get
  match 'api/0.6/relations/search' => 'search#search_relations', :via => :get
  match 'api/0.6/nodes/search' => 'search#search_nodes', :via => :get

  match 'api/0.6/user/:id' => 'user#api_read', :via => :get, :id => /\d+/
  match 'api/0.6/user/details' => 'user#api_details', :via => :get
  match 'api/0.6/user/gpx_files' => 'user#api_gpx_files', :via => :get

  match 'api/0.6/user/preferences' => 'user_preference#read', :via => :get
  match 'api/0.6/user/preferences/:preference_key' => 'user_preference#read_one', :via => :get
  match 'api/0.6/user/preferences' => 'user_preference#update', :via => :put
  match 'api/0.6/user/preferences/:preference_key' => 'user_preference#update_one', :via => :put
  match 'api/0.6/user/preferences/:preference_key' => 'user_preference#delete_one', :via => :delete

  match 'api/0.6/gpx/create' => 'trace#api_create', :via => :post
  match 'api/0.6/gpx/:id' => 'trace#api_read', :via => :get, :id => /\d+/
  match 'api/0.6/gpx/:id' => 'trace#api_update', :via => :put, :id => /\d+/
  match 'api/0.6/gpx/:id' => 'trace#api_delete', :via => :delete, :id => /\d+/
  match 'api/0.6/gpx/:id/details' => 'trace#api_read', :via => :get, :id => /\d+/
  match 'api/0.6/gpx/:id/data' => 'trace#api_data', :via => :get
  
  # AMF (ActionScript) API
  match 'api/0.6/amf/read' => 'amf#amf_read', :via => :post
  match 'api/0.6/amf/write' => 'amf#amf_write', :via => :post
  match 'api/0.6/swf/trackpoints' => 'swf#trackpoints', :via => :get

  # Map notes API
  scope "api/0.6" do
    resources :notes, :except => [ :new, :edit, :update ], :constraints => { :id => /\d+/ }, :defaults => { :format => "xml" } do
      collection do
        get 'search'
        get 'feed', :defaults => { :format => "rss" }
      end

      member do
        post 'comment'
        post 'close'
        post 'reopen'
      end
    end

    match 'notes/addPOIexec' => 'notes#create', :via => :post
    match 'notes/closePOIexec' => 'notes#close', :via => :post
    match 'notes/editPOIexec' => 'notes#comment', :via => :post
    match 'notes/getGPX' => 'notes#index', :via => :get, :format => "gpx"
    match 'notes/getRSSfeed' => 'notes#feed', :via => :get, :format => "rss"
  end

  # Data browsing
  match '/way/:id' => 'browse#way', :via => :get, :id => /\d+/, :as => :way
  match '/way/:id/history' => 'browse#way_history', :via => :get, :id => /\d+/
  match '/node/:id' => 'browse#node', :via => :get, :id => /\d+/, :as => :node
  match '/node/:id/history' => 'browse#node_history', :via => :get, :id => /\d+/
  match '/relation/:id' => 'browse#relation', :via => :get, :id => /\d+/, :as => :relation
  match '/relation/:id/history' => 'browse#relation_history', :via => :get, :id => /\d+/
  match '/changeset/:id' => 'browse#changeset', :via => :get, :as => :changeset, :id => /\d+/
  match '/changeset/:id/comments/feed' => 'changeset#comments_feed', :via => :get, :as => :changeset_comments_feed, :id => /\d*/, :defaults => { :format => 'rss' }
  match '/note/:id' => 'browse#note', :via => :get, :id => /\d+/, :as => "browse_note"
  match '/note/new' => 'browse#new_note', :via => :get
  match '/user/:display_name/history' => 'changeset#list', :via => :get
  match '/user/:display_name/history/feed' => 'changeset#feed', :via => :get, :defaults => { :format => :atom }
  match '/user/:display_name/notes' => 'notes#mine', :via => :get
  match '/history/friends' => 'changeset#list', :via => :get, :friends => true, :as => "friend_changesets"
  match '/history/nearby' => 'changeset#list', :via => :get, :nearby => true, :as => "nearby_changesets"

  get '/browse/way/:id',                :to => redirect(:path => '/way/%{id}')
  get '/browse/way/:id/history',        :to => redirect(:path => '/way/%{id}/history')
  get '/browse/node/:id',               :to => redirect(:path => '/node/%{id}')
  get '/browse/node/:id/history',       :to => redirect(:path => '/node/%{id}/history')
  get '/browse/relation/:id',           :to => redirect(:path => '/relation/%{id}')
  get '/browse/relation/:id/history',   :to => redirect(:path => '/relation/%{id}/history')
  get '/browse/changeset/:id',          :to => redirect(:path => '/changeset/%{id}')
  get '/browse/note/:id',               :to => redirect(:path => '/note/%{id}')
  get '/user/:display_name/edits',      :to => redirect(:path => '/user/%{display_name}/history')
  get '/user/:display_name/edits/feed', :to => redirect(:path => '/user/%{display_name}/history/feed')
  get '/browse/friends',                :to => redirect(:path => '/history/friends')
  get '/browse/nearby',                 :to => redirect(:path => '/history/nearby')
  get '/browse/changesets/feed',        :to => redirect(:path => '/history/feed')
  get '/browse/changesets',             :to => redirect(:path => '/history')
  get '/browse',                        :to => redirect(:path => '/history')

  # web site
  root :to => 'site#index', :via => [:get, :post]
  match '/edit' => 'site#edit', :via => :get, :as => :edit
  match '/copyright/:copyright_locale' => 'site#copyright', :via => :get
  match '/copyright' => 'site#copyright', :via => :get
  match '/welcome' => 'site#welcome', :via => :get, :as => :welcome
  match '/fixthemap' => 'site#fixthemap', :via => :get, :as => :fixthemap
  match '/help' => 'site#help', :via => :get, :as => :help
  match '/about' => 'site#about', :via => :get, :as => :about
  match '/history' => 'changeset#list', :via => :get
  match '/history/feed' => 'changeset#feed', :via => :get, :defaults => { :format => :atom }
  match '/history/comments/feed' => 'changeset#comments_feed', :via => :get, :as => :changesets_comments_feed, :defaults => { :format => 'rss' }
  match '/export' => 'site#export', :via => :get
  match '/login' => 'user#login', :via => [:get, :post]
  match '/logout' => 'user#logout', :via => [:get, :post]
  match '/offline' => 'site#offline', :via => :get
  match '/key' => 'site#key', :via => :get
  match '/id' => 'site#id', :via => :get
  match '/query' => 'browse#query', :via => :get
  match '/user/new' => 'user#new', :via => :get
  match '/user/new' => 'user#create', :via => :post
  match '/user/terms' => 'user#terms', :via => :get
  match '/user/save' => 'user#save', :via => :post
  match '/user/:display_name/confirm/resend' => 'user#confirm_resend', :via => :get
  match '/user/:display_name/confirm' => 'user#confirm', :via => [:get, :post]
  match '/user/confirm' => 'user#confirm', :via => [:get, :post]
  match '/user/confirm-email' => 'user#confirm_email', :via => [:get, :post]
  match '/user/go_public' => 'user#go_public', :via => :post
  match '/user/reset-password' => 'user#reset_password', :via => [:get, :post]
  match '/user/forgot-password' => 'user#lost_password', :via => [:get, :post]
  match '/user/suspended' => 'user#suspended', :via => :get

  get '/index.html', :to => redirect(:path => "/")
  get '/create-account.html', :to => redirect(:path => "/user/new")
  get '/forgot-password.html', :to => redirect(:path => "/user/forgot-password")

  # permalink
  match '/go/:code' => 'site#permalink', :via => :get, :code => /[a-zA-Z0-9_@~]+[=-]*/

  # rich text preview
  match '/preview/:format' => 'site#preview', :via => :post, :as => :preview

  # traces
  match '/user/:display_name/traces/tag/:tag/page/:page' => 'trace#list', :via => :get
  match '/user/:display_name/traces/tag/:tag' => 'trace#list', :via => :get
  match '/user/:display_name/traces/page/:page' => 'trace#list', :via => :get
  match '/user/:display_name/traces' => 'trace#list', :via => :get
  match '/user/:display_name/traces/tag/:tag/rss' => 'trace#georss', :via => :get, :defaults => { :format => :rss }
  match '/user/:display_name/traces/rss' => 'trace#georss', :via => :get, :defaults => { :format => :rss }
  match '/user/:display_name/traces/:id' => 'trace#view', :via => :get
  match '/user/:display_name/traces/:id/picture' => 'trace#picture', :via => :get
  match '/user/:display_name/traces/:id/icon' => 'trace#icon', :via => :get
  match '/traces/tag/:tag/page/:page' => 'trace#list', :via => :get
  match '/traces/tag/:tag' => 'trace#list', :via => :get
  match '/traces/page/:page' => 'trace#list', :via => :get
  match '/traces' => 'trace#list', :via => :get
  match '/traces/tag/:tag/rss' => 'trace#georss', :via => :get, :defaults => { :format => :rss }
  match '/traces/rss' => 'trace#georss', :via => :get, :defaults => { :format => :rss }
  match '/traces/mine/tag/:tag/page/:page' => 'trace#mine', :via => :get
  match '/traces/mine/tag/:tag' => 'trace#mine', :via => :get
  match '/traces/mine/page/:page' => 'trace#mine', :via => :get
  match '/traces/mine' => 'trace#mine', :via => :get
  match '/trace/create' => 'trace#create', :via => [:get, :post]
  match '/trace/:id/data' => 'trace#data', :via => :get, :id => /\d+/, :as => "trace_data"

app/helpers/browse_helper.rb
module BrowseHelper
  def printable_name(object, version=false)
    if object.id.is_a?(Array)
      id = object.id[0]
    else
      id = object.id
    end
    name = t 'printable_name.with_id', :id => id.to_s
    if version
      name = t 'printable_name.with_version', :id => name, :version => object.version.to_s
    end

    # don't look at object tags if redacted, so as to avoid giving
    # away redacted version tag information.
    unless object.redacted?
      locale = I18n.locale.to_s

      while locale =~ /-[^-]+/ and not object.tags.include? "name:#{I18n.locale}"
        locale = locale.sub(/-[^-]+/, "")
      end

      if object.tags.include? "name:#{locale}"
        name = t 'printable_name.with_name_html', :name => content_tag(:bdi, object.tags["name:#{locale}"].to_s ), :id => content_tag(:bdi, name)
      elsif object.tags.include? 'name'
        name = t 'printable_name.with_name_html', :name => content_tag(:bdi, object.tags['name'].to_s ), :id => content_tag(:bdi, name)
      end
    end

    name
  end

  def link_class(type, object)
    classes = [ type ]

    if object.redacted?
      classes << "deleted"
    else
      classes += icon_tags(object).flatten.map { |t| h(t) }
      classes << "deleted" unless object.visible?
    end

    classes.join(" ")
  end

  def link_title(object)
    if object.redacted?
      ""
    else
      h(icon_tags(object).map { |k,v| k + '=' + v }.to_sentence)
    end
  end

  def format_key(key)
    if url = wiki_link("key", key)
      link_to h(key), url, :title => t('browse.tag_details.wiki_link.key', :key => key)
    else
      h(key)
    end
  end

  def format_value(key, value)
    if wp = wikipedia_link(key, value)
      link_to h(wp[:title]), wp[:url], :title => t('browse.tag_details.wikipedia_link', :page => wp[:title])
    elsif wdt = wikidata_link(key, value)
      link_to h(wdt[:title]), wdt[:url], :title => t('browse.tag_details.wikidata_link', :page => wdt[:title])
    elsif url = wiki_link("tag", "#{key}=#{value}")
      link_to h(value), url, :title => t('browse.tag_details.wiki_link.tag', :key => key, :value => value)
    elsif url = telephone_link(key, value)
      link_to h(value), url, :title => t('browse.tag_details.telephone_link', :phone_number => value)
    else
      linkify h(value)
    end
  end

  def type_and_paginated_count(type, pages)
    if pages.page_count == 1
      t "browse.changeset.#{type}",
        :count => pages.item_count
    else
      t "browse.changeset.#{type}_paginated",
        :x => pages.current_page.first_item,
        :y => pages.current_page.last_item,
        :count => pages.item_count
    end
  end

private

  ICON_TAGS = [
    "aeroway", "amenity", "barrier", "building", "highway", "historic", "landuse",
    "leisure", "man_made", "natural", "railway", "shop", "tourism", "waterway"
  ]

  def icon_tags(object)
    object.tags.find_all { |k,v| ICON_TAGS.include? k }.sort
  end

  def wiki_link(type, lookup)
    locale = I18n.locale.to_s

    # update-wiki-pages does s/ /_/g on keys before saving them, we
    # have to replace spaces with underscore so we'll link
    # e.g. `source=Isle of Man Government aerial imagery (2001)' to
    # the correct page.
    lookup_us = lookup.tr(" ", "_")

    if page = WIKI_PAGES[locale][type][lookup_us] rescue nil
      url = "http://wiki.openstreetmap.org/wiki/#{page}?uselang=#{locale}"
    elsif page = WIKI_PAGES["en"][type][lookup_us] rescue nil
      url = "http://wiki.openstreetmap.org/wiki/#{page}?uselang=#{locale}"
    end

    return url
  end

  def wikipedia_link(key, value)
    # Some k/v's are wikipedia=http://en.wikipedia.org/wiki/Full%20URL
    return nil if value =~ /^https?:\/\//

    if key == "wikipedia"
      # This regex should match Wikipedia language codes, everything
      # from de to zh-classical
      if value =~ /^([a-z-]{2,12}):(.+)$/i
        # Value is <lang>:<title> so split it up
        # Note that value is always left as-is, see: https://trac.openstreetmap.org/ticket/4315
        lang  = $1
      else
        # Value is <title> so default to English Wikipedia
        lang = 'en'
      end
    elsif key =~ /^wikipedia:(\S+)$/
      # Language is in the key, so assume value is the title
      lang = $1
    else
      # Not a wikipedia key!
      return nil
    end

    if value =~ /^([^#]*)(#.*)/ then
      # Contains a reference to a section of the wikipedia article
      # Must break it up to correctly build the url
      value = $1
      section = $2
    else
      section = ""
    end

    return {
      :url => "http://#{lang}.wikipedia.org/wiki/#{value}?uselang=#{I18n.locale}#{section}",
      :title => value + section
    }
  end

  def wikidata_link(key, value)
    if key == "wikidata" and value =~ /^[Qq][1-9][0-9]*$/
      return {
        :url => "//www.wikidata.org/wiki/#{value}?uselang=#{I18n.locale}",
        :title => value
      }
    end
    return nil
  end

  def telephone_link(key, value)
    # does it look like a phone number? eg "+1 (234) 567-8901 " ?
    return nil unless value =~ /^\s*\+[\d\s\(\)\/\.-]{6,25}\s*$/

    # remove all whitespace instead of encoding it http://tools.ietf.org/html/rfc3966#section-5.1.1
    # "+1 (234) 567-8901 " -> "+1(234)567-8901"
    valueNoWhitespace = value.gsub(/\s+/, '')

    return "tel:#{valueNoWhitespace}"
  end
end

app/views/browse/_common_details.html.erb
<h4>
  <% if common_details.changeset.tags['comment'].present? %>
    <%= linkify(h(common_details.changeset.tags['comment'])) %>
  <% else %>
    <%= t 'browse.no_comment' %>
  <% end %>
</h4>

<div class="details">
  <%=
      t "browse.#{common_details.visible? ? :edited : :deleted}_by_html",
        :time => distance_of_time_in_words_to_now(common_details.timestamp),
        :user => changeset_user_link(common_details.changeset),
        :title => l(common_details.timestamp)
  %>
</div>

<div class="details">
  <%= t 'browse.version' %>
  #<%= h(common_details.version) %>
  &middot;
  <%= t 'browse.in_changeset' %>
  #<%= link_to common_details.changeset_id, :action => :changeset, :id => common_details.changeset_id %>
</div>

<% if @type == "node" and common_details.visible? %>
<div class="details geo">
  <%= t 'browse.location' %>
  <%= link_to(content_tag(:span, number_with_delimiter(common_details.lat), :class => "latitude") + ", " + content_tag(:span, number_with_delimiter(common_details.lon), :class => "longitude"), {:controller => 'site', :action => 'index', :anchor => "map=18/#{common_details.lat}/#{common_details.lon}"}) %>
</div>
<% end %>

<%= render :partial => "tag_details", :object => common_details.tags %>

app/views/browse/_containing_relation.html.erb
<li><%=
  linked_name = link_to h(printable_name(containing_relation.relation)), :action => "relation", :id => containing_relation.relation.id.to_s
  if containing_relation.member_role.blank?
    raw t 'browse.containing_relation.entry', :relation_name => linked_name
  else
    raw t 'browse.containing_relation.entry_role', :relation_name => linked_name, :relation_role => h(containing_relation.member_role)
  end
%></li>

app/views/browse/_node.html.erb
<% if node.redacted? %>
  <div class='browse-section browse-redacted'>
    <%= t 'browse.redacted.message_html',
          :type => t('browse.redacted.type.node'),
          :version => node.version,
          :redaction_link => link_to(t('browse.redacted.redaction',
                                       :id => node.redaction.id), node.redaction) %>
  </div>
<% else %>
  <div class='browse-section browse-node'>
    <%= render :partial => "common_details", :object => node %>

    <% unless node.ways.empty? and node.containing_relation_members.empty? %>
      <h4><%= t 'browse.part_of' %></h4>
      <ul>
        <% node.ways.uniq.each do |way| %>
          <li><%= link_to printable_name(way), { :action => "way", :id => way.id.to_s }, :class => link_class('way', way), :title => link_title(way) %></li>
        <% end %>
        <%= render :partial => "containing_relation", :collection => node.containing_relation_members.uniq %>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/browse/_paging_nav.html.erb
<% if pages.page_count > 1 %>
  <span class="paginate">
    <%= raw pagination_links_each(pages, {}) { |n| link_to(n, page_param => n) } %>
  </span>
<% end %>

app/views/browse/_relation.html.erb
<% if relation.redacted? %>
  <div class='browse-section browse-redacted'>
    <%= t 'browse.redacted.message_html',
          :type => t('browse.redacted.type.relation'),
          :version => relation.version,
          :redaction_link => link_to(t('browse.redacted.redaction',
                                       :id => relation.redaction.id), relation.redaction) %>
  </div>
<% else %>
  <div class='browse-section browse-relation'>
    <%= render :partial => "common_details", :object => relation %>

    <% unless relation.relation_members.empty? %>
      <h4><%= t'browse.relation.members' %></h4>
      <ul><%= render :partial => "relation_member", :collection => relation.relation_members %></ul>
    <% end %>

    <% unless relation.containing_relation_members.empty? %>
      <h4><%= t'browse.part_of' %></h4>
      <ul><%= render :partial => "containing_relation", :collection => relation.containing_relation_members.uniq %></ul>
    <% end %>
  </div>
<% end %>

app/views/browse/_relation_member.html.erb
<%
  member_class = link_class(relation_member.member_type.downcase, relation_member.member)
  linked_name = link_to printable_name(relation_member.member), { :action => relation_member.member_type.downcase, :id => relation_member.member_id.to_s }, :title => link_title(relation_member.member)
  type_str = t'browse.relation_member.type.' + relation_member.member_type.downcase
%>
  <li class="<%= member_class %>"><%=
    if relation_member.member_role.blank?
      raw t'browse.relation_member.entry', :type => type_str, :name => linked_name
    else
      raw t'browse.relation_member.entry_role', :type => type_str, :name => linked_name, :role => h(relation_member.member_role)
    end
  %></li>

app/views/browse/_tag.html.erb
<tr>
  <th class='browse-tag-k'><%= format_key(tag[0]) %></th>
  <td class='browse-tag-v'><%= format_value(tag[0], tag[1]) %></td>
</tr>

app/views/browse/_tag_details.html.erb
<% unless tag_details.empty? %>
  <h4><%= t 'browse.tag_details.tags' %></h4>
  <table class='browse-tag-list'>
    <%= render :partial => "tag", :collection => tag_details.sort %>
  </table>
<% end %>

app/views/browse/_way.html.erb
<% if way.redacted? %>
  <div class='browse-section browse-redacted'>
    <%= t 'browse.redacted.message_html',
          :type => t('browse.redacted.type.way'),
          :version => way.version,
          :redaction_link => link_to(t('browse.redacted.redaction',
                                       :id => way.redaction.id), way.redaction) %>
  </div>
<% else %>
  <div class='browse-section browse-way'>
    <%= render :partial => "common_details", :object => way %>

    <% unless way.way_nodes.empty? %>
      <h4><%= t'browse.way.nodes' %></h4>
      <ul>
        <% way.way_nodes.each do |wn| %>
          <li>
            <%= link_to printable_name(wn.node), { :action => "node", :id => wn.node_id.to_s }, :class => link_class('node', wn.node), :title => link_title(wn.node) %>
            <% related_ways = wn.node.ways.reject { |w| w.id == wn.way_id } %>
            <% if related_ways.size > 0 then %>
              (<%= raw t 'browse.way.also_part_of', :count => related_ways.size, :related_ways => related_ways.map { |w| link_to(printable_name(w), { :action => "way", :id => w.id.to_s }, :class => link_class('way', w), :title => link_title(w) ) }.to_sentence %>)
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <% unless way.containing_relation_members.empty? %>
      <h4><%= t'browse.part_of' %></h4>
      <ul>
        <%= render :partial => "containing_relation", :collection => way.containing_relation_members.uniq %>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/browse/new_note.html.erb
<% set_title(t "browse.note.new_note") %>

<h2>
  <a class="geolink" href="<%= root_path %>"><span class="icon close"></span></a>
  <%= t "browse.note.new_note" %>
</h2>

<div class="note browse-section">
  <p class="warning"><%= t('javascripts.notes.new.intro') %></p>
  <form action="#">
    <input type="hidden" name="lon">
    <input type="hidden" name="lat">
    <textarea class="comment" name="text" cols="40" rows="10"></textarea>
    <div class="buttons clearfix">
      <input type="submit" name="add" value="<%= t('javascripts.notes.new.add') %>" disabled="1">
    </div>
  </form>
</div>

app/views/browse/not_found.html.erb
<%
  browse_not_found_type = {
    'node' => I18n.t('browse.not_found.type.node'),
    'way' => I18n.t('browse.not_found.type.way'),
    'relation' => I18n.t('browse.not_found.type.relation'),
    'changeset' => I18n.t('browse.not_found.type.changeset'),
  };
%>

<h2>
    <a class="geolink" href="<%= root_path %>"><span class="icon close"></span></a>
    <%= t'browse.not_found.sorry', :type=> browse_not_found_type[@type] , :id => params[:id] %></h2>

app/views/browse/note.html.erb
<% set_title(t('browse.note.title', :id => @note.id)) %>

<h2>
  <a class="geolink" href="<%= root_path %>"><span class="icon close"></span></a>
  <%= t "browse.note.#{@note.status}_title", :note_name => @note.id %>
</h2>

<div class="browse-section">
  <h4><%= t('browse.note.description') %></h4>
  <div class="note-description">
    <%= h(@note.comments.first.body.to_html) %>
  </div>

  <div class="details" data-coordinates="<%= @note.lat %>,<%= @note.lon %>" data-status="<%= @note.status %>">
    <%= note_event('open', @note.created_at, @note.author) %>
    <% if @note.status == "closed" %>
      <br/>
      <%= note_event(@note.status, @note.closed_at, @note.comments.last.author) %>
    <% end %>
  </div>

  <% if @note.comments.find { |comment| comment.author.nil? } -%>
    <p class='warning'><%= t "javascripts.notes.show.anonymous_warning" %></p>
  <% end -%>

  <% if @note.comments.length > 1 %>
    <div class='note-comments'>
      <ul>
        <% @note.comments[1..-1].each do |comment| %>
          <li id="c<%= comment.id %>">
            <small class='deemphasize'><%= note_event(comment.event, comment.created_at, comment.author) %></small>
            <%= comment.body.to_html %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @note.status == "open" %>
    <form action="#">
      <textarea class="comment" name="text" cols="40" rows="5"></textarea>
      <div class="buttons clearfix">
        <input type="submit" name="hide" value="<%= t('javascripts.notes.show.hide') %>" class="hide_unless_moderator deemphasize" data-note-id="<%= @note.id %>" data-method="DELETE" data-url="<%= note_url(@note, 'json') %>">
        <input type="submit" name="close" value="<%= t('javascripts.notes.show.resolve') %>" class="hide_unless_logged_in" data-note-id="<%= @note.id %>" data-method="POST" data-url="<%= close_note_url(@note, 'json') %>">
        <input type="submit" name="comment" value="<%= t('javascripts.notes.show.comment') %>" data-note-id="<%= @note.id %>" data-method="POST" data-url="<%= comment_note_url(@note, 'json') %>" disabled="1">
      </div>
    </form>
  <% else %>
    <form action="#">
      <input type="hidden" name="text" value="">
      <div class="buttons clearfix">
        <input type="submit" name="hide" value="<%= t('javascripts.notes.show.hide') %>" class="hide_unless_moderator deemphasize" data-note-id="<%= @note.id %>" data-method="DELETE" data-url="<%= note_url(@note, 'json') %>">
        <input type="submit" name="reopen" value="<%= t('javascripts.notes.show.reactivate') %>" class="hide_unless_logged_in" data-note-id="<%= @note.id %>" data-method="POST" data-url="<%= reopen_note_url(@note, 'json') %>">
      </div>
    </form>
  <% end %>
</div>

app/views/browse/query.html.erb
<% set_title(t "browse.query.title") %>

<h2>
  <a class="geolink" href="<%= root_path %>"><span class="icon close"></span></a>
  <%= t "browse.query.title" %>
</h2>

<div class="query-intro">
  <p><%= t("browse.query.introduction") %></p>
</div>

<div id="query-nearby" class="query-results">
  <h3><%= t("browse.query.nearby") %></h3>
  <%= image_tag "searching.gif", :class => "loader" %>
  <ul class="query-results-list"></ul>
</div>

<div id="query-isin" class="query-results">
  <h3><%= t("browse.query.enclosing") %></h3>
  <%= image_tag "searching.gif", :class => "loader" %>
  <ul class="query-results-list"></ul>
</div>

app/views/browse/timeout.html.erb
<%
  browse_timeout_type = {
    'node' => I18n.t('browse.timeout.type.node'),
    'way' => I18n.t('browse.timeout.type.way'),
    'relation' => I18n.t('browse.timeout.type.relation'),
    'changeset' => I18n.t('browse.timeout.type.changeset'),
  };
%>
<p><%= t'browse.timeout.sorry', :type=> browse_timeout_type[@type] , :id => params[:id] %></p>