config/routes.rb
  match 'api/0.6/changesets' => 'changeset#query', :via => :get
  post 'api/0.6/changeset/:id/comment' => 'changeset#comment', :as => :changeset_comment, :id => /\d+/
  post 'api/0.6/changeset/comment/:id/hide' => 'changeset#hide_comment', :as => :changeset_comment_hide, :id => /\d+/
  post 'api/0.6/changeset/comment/:id/unhide' => 'changeset#unhide_comment', :as => :changeset_comment_unhide, :id => /\d+/

  match 'api/0.6/node/create' => 'node#create', :via => :put
  match 'api/0.6/node/:id/ways' => 'way#ways_for_node', :via => :get, :id => /\d+/
  match 'api/0.6/node/:id/relations' => 'relation#relations_for_node', :via => :get, :id => /\d+/
  match 'api/0.6/node/:id/history' => 'old_node#history', :via => :get, :id => /\d+/
  match 'api/0.6/node/:id/:version/redact' => 'old_node#redact', :via => :post, :version => /\d+/, :id => /\d+/
  match 'api/0.6/node/:id/:version' => 'old_node#version', :via => :get, :id => /\d+/, :version => /\d+/
  match 'api/0.6/node/:id' => 'node#read', :via => :get, :id => /\d+/
  match 'api/0.6/node/:id' => 'node#update', :via => :put, :id => /\d+/
  match 'api/0.6/node/:id' => 'node#delete', :via => :delete, :id => /\d+/
  match 'api/0.6/nodes' => 'node#nodes', :via => :get

  match 'api/0.6/way/create' => 'way#create', :via => :put
  match 'api/0.6/way/:id/history' => 'old_way#history', :via => :get, :id => /\d+/
  match 'api/0.6/way/:id/full' => 'way#full', :via => :get, :id => /\d+/
  match 'api/0.6/way/:id/relations' => 'relation#relations_for_way', :via => :get, :id => /\d+/
  match 'api/0.6/way/:id/:version/redact' => 'old_way#redact', :via => :post, :version => /\d+/, :id => /\d+/
  match 'api/0.6/way/:id/:version' => 'old_way#version', :via => :get, :id => /\d+/, :version => /\d+/
  match 'api/0.6/way/:id' => 'way#read', :via => :get, :id => /\d+/
  match 'api/0.6/way/:id' => 'way#update', :via => :put, :id => /\d+/
  match 'api/0.6/way/:id' => 'way#delete', :via => :delete, :id => /\d+/
  match 'api/0.6/ways' => 'way#ways', :via => :get

  match 'api/0.6/relation/create' => 'relation#create', :via => :put
  match 'api/0.6/relation/:id/relations' => 'relation#relations_for_relation', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id/history' => 'old_relation#history', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id/full' => 'relation#full', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id/:version/redact' => 'old_relation#redact', :via => :post, :version => /\d+/, :id => /\d+/
  match 'api/0.6/relation/:id/:version' => 'old_relation#version', :via => :get, :id => /\d+/, :version => /\d+/
  match 'api/0.6/relation/:id' => 'relation#read', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id' => 'relation#update', :via => :put, :id => /\d+/
  match 'api/0.6/relation/:id' => 'relation#delete', :via => :delete, :id => /\d+/
  match 'api/0.6/relations' => 'relation#relations', :via => :get

  match 'api/0.6/map' => 'api#map', :via => :get

  match 'api/0.6/trackpoints' => 'api#trackpoints', :via => :get

  match 'api/0.6/changes' => 'api#changes', :via => :get

  match 'api/0.6/search' => 'search#search_all', :via => :get
  match 'api/0.6/ways/search' => 'search#search_ways', :via => :get
  match 'api/0.6/relations/search' => 'search#search_relations', :via => :get
  match 'api/0.6/nodes/search' => 'search#search_nodes', :via => :get

  match 'api/0.6/user/:id' => 'user#api_read', :via => :get, :id => /\d+/
  match 'api/0.6/user/details' => 'user#api_details', :via => :get
  match 'api/0.6/user/gpx_files' => 'user#api_gpx_files', :via => :get

  match 'api/0.6/user/preferences' => 'user_preference#read', :via => :get
  match 'api/0.6/user/preferences/:preference_key' => 'user_preference#read_one', :via => :get
  match 'api/0.6/user/preferences' => 'user_preference#update', :via => :put
  match 'api/0.6/user/preferences/:preference_key' => 'user_preference#update_one', :via => :put
  match 'api/0.6/user/preferences/:preference_key' => 'user_preference#delete_one', :via => :delete

  match 'api/0.6/gpx/create' => 'trace#api_create', :via => :post
  match 'api/0.6/gpx/:id' => 'trace#api_read', :via => :get, :id => /\d+/
  match 'api/0.6/gpx/:id' => 'trace#api_update', :via => :put, :id => /\d+/
  match 'api/0.6/gpx/:id' => 'trace#api_delete', :via => :delete, :id => /\d+/
  match 'api/0.6/gpx/:id/details' => 'trace#api_read', :via => :get, :id => /\d+/
  match 'api/0.6/gpx/:id/data' => 'trace#api_data', :via => :get
  
  # AMF (ActionScript) API
  match 'api/0.6/amf/read' => 'amf#amf_read', :via => :post
  match 'api/0.6/amf/write' => 'amf#amf_write', :via => :post
  match 'api/0.6/swf/trackpoints' => 'swf#trackpoints', :via => :get

  # Map notes API
  scope "api/0.6" do
    resources :notes, :except => [ :new, :edit, :update ], :constraints => { :id => /\d+/ }, :defaults => { :format => "xml" } do
      collection do
        get 'search'
        get 'feed', :defaults => { :format => "rss" }
      end

      member do
        post 'comment'
        post 'close'
        post 'reopen'
      end
    end

    match 'notes/addPOIexec' => 'notes#create', :via => :post
    match 'notes/closePOIexec' => 'notes#close', :via => :post
    match 'notes/editPOIexec' => 'notes#comment', :via => :post
    match 'notes/getGPX' => 'notes#index', :via => :get, :format => "gpx"
    match 'notes/getRSSfeed' => 'notes#feed', :via => :get, :format => "rss"
  end

  # Data browsing
  match '/way/:id' => 'browse#way', :via => :get, :id => /\d+/, :as => :way
  match '/way/:id/history' => 'browse#way_history', :via => :get, :id => /\d+/
  match '/node/:id' => 'browse#node', :via => :get, :id => /\d+/, :as => :node
  match '/node/:id/history' => 'browse#node_history', :via => :get, :id => /\d+/
  match '/relation/:id' => 'browse#relation', :via => :get, :id => /\d+/, :as => :relation
  match '/relation/:id/history' => 'browse#relation_history', :via => :get, :id => /\d+/
  match '/changeset/:id' => 'browse#changeset', :via => :get, :as => :changeset, :id => /\d+/
  match '/changeset/:id/comments/feed' => 'changeset#comments_feed', :via => :get, :as => :changeset_comments_feed, :id => /\d*/, :defaults => { :format => 'rss' }
  match '/note/:id' => 'browse#note', :via => :get, :id => /\d+/, :as => "browse_note"
  match '/note/new' => 'browse#new_note', :via => :get
  match '/user/:display_name/history' => 'changeset#list', :via => :get
  match '/user/:display_name/history/feed' => 'changeset#feed', :via => :get, :defaults => { :format => :atom }
  match '/user/:display_name/notes' => 'notes#mine', :via => :get
  match '/history/friends' => 'changeset#list', :via => :get, :friends => true, :as => "friend_changesets"
  match '/history/nearby' => 'changeset#list', :via => :get, :nearby => true, :as => "nearby_changesets"

  get '/browse/way/:id',                :to => redirect(:path => '/way/%{id}')
  get '/browse/way/:id/history',        :to => redirect(:path => '/way/%{id}/history')
  get '/browse/node/:id',               :to => redirect(:path => '/node/%{id}')
  get '/browse/node/:id/history',       :to => redirect(:path => '/node/%{id}/history')
  get '/browse/relation/:id',           :to => redirect(:path => '/relation/%{id}')
  get '/browse/relation/:id/history',   :to => redirect(:path => '/relation/%{id}/history')
  get '/browse/changeset/:id',          :to => redirect(:path => '/changeset/%{id}')
  get '/browse/note/:id',               :to => redirect(:path => '/note/%{id}')
  get '/user/:display_name/edits',      :to => redirect(:path => '/user/%{display_name}/history')
  get '/user/:display_name/edits/feed', :to => redirect(:path => '/user/%{display_name}/history/feed')
  get '/browse/friends',                :to => redirect(:path => '/history/friends')
  get '/browse/nearby',                 :to => redirect(:path => '/history/nearby')
  get '/browse/changesets/feed',        :to => redirect(:path => '/history/feed')
  get '/browse/changesets',             :to => redirect(:path => '/history')
  get '/browse',                        :to => redirect(:path => '/history')

  # web site
  root :to => 'site#index', :via => [:get, :post]
  match '/edit' => 'site#edit', :via => :get, :as => :edit
  match '/copyright/:copyright_locale' => 'site#copyright', :via => :get
  match '/copyright' => 'site#copyright', :via => :get
  match '/welcome' => 'site#welcome', :via => :get, :as => :welcome
  match '/fixthemap' => 'site#fixthemap', :via => :get, :as => :fixthemap
  match '/help' => 'site#help', :via => :get, :as => :help
  match '/about' => 'site#about', :via => :get, :as => :about
  match '/history' => 'changeset#list', :via => :get
  match '/history/feed' => 'changeset#feed', :via => :get, :defaults => { :format => :atom }
  match '/history/comments/feed' => 'changeset#comments_feed', :via => :get, :as => :changesets_comments_feed, :defaults => { :format => 'rss' }
  match '/export' => 'site#export', :via => :get
  match '/login' => 'user#login', :via => [:get, :post]
  match '/logout' => 'user#logout', :via => [:get, :post]
  match '/offline' => 'site#offline', :via => :get
  match '/key' => 'site#key', :via => :get
  match '/id' => 'site#id', :via => :get
  match '/query' => 'browse#query', :via => :get
  match '/user/new' => 'user#new', :via => :get
  match '/user/new' => 'user#create', :via => :post
  match '/user/terms' => 'user#terms', :via => :get
  match '/user/save' => 'user#save', :via => :post
  match '/user/:display_name/confirm/resend' => 'user#confirm_resend', :via => :get
  match '/user/:display_name/confirm' => 'user#confirm', :via => [:get, :post]
  match '/user/confirm' => 'user#confirm', :via => [:get, :post]
  match '/user/confirm-email' => 'user#confirm_email', :via => [:get, :post]
  match '/user/go_public' => 'user#go_public', :via => :post
  match '/user/reset-password' => 'user#reset_password', :via => [:get, :post]
  match '/user/forgot-password' => 'user#lost_password', :via => [:get, :post]
  match '/user/suspended' => 'user#suspended', :via => :get

app/helpers/user_helper.rb
module UserHelper
  # User images

  def user_image(user, options = {})
    options[:class] ||= "user_image"
    options[:alt] ||= ""

    if user.image_use_gravatar
      user_gravatar_tag(user, options)
    else
      image_tag user.image.url(:large), options
    end
  end

  def user_thumbnail(user, options = {})
    options[:class] ||= "user_thumbnail"
    options[:alt] ||= ""

    if user.image_use_gravatar
      user_gravatar_tag(user, options)
    else
      image_tag user.image.url(:small), options
    end
  end

  def user_thumbnail_tiny(user, options = {})
    options[:class] ||= "user_thumbnail_tiny"
    options[:alt] ||= ""

    if user.image_use_gravatar
      user_gravatar_tag(user, options)
    else
      image_tag user.image.url(:small), options
    end
  end

  def user_image_url(user, options = {})
    if user.image_use_gravatar
      user_gravatar_url(user, options)
    else
      image_url(user.image.url)
    end
  end

  # OpenID support

  def openid_logo
    image_tag "openid_small.png", :alt => t('user.login.openid_logo_alt'), :class => "openid_logo"
  end

  def openid_button(name, url)
    link_to(
      image_tag("#{name}.png", :alt => t("user.login.openid_providers.#{name}.alt")),
      "#",
      :class => "openid_button", :data => { :url => url },
      :title => t("user.login.openid_providers.#{name}.title")
    )
  end

  # Gravatar support

  # See http://en.gravatar.com/site/implement/images/ for details.
  def user_gravatar_url(user, options = {})
    size = options[:size] || 100
    hash = Digest::MD5::hexdigest(user.email.downcase)
    default_image_url = image_url("users/images/large.png")
    url = "#{request.protocol}www.gravatar.com/avatar/#{hash}.jpg?s=#{size}&d=#{u(default_image_url)}"
  end

  def user_gravatar_tag(user, options = {})
    url = user_gravatar_url(user, options)
    options.delete(:size)
    image_tag url, options
  end
end

app/views/user/_popup.html.erb
<div class="user_popup">
  <%= user_thumbnail popup %>
  <p><%= t('user.popup.' + type) %></p>
  <p><%= link_to popup.display_name, :controller => "user", :action => "view", :display_name => popup.display_name %></p>
</div>

app/views/user/_terms.html.erb
<p id="first">
  <%= raw @text['intro'] %>
  <%= raw @text['next_with_decline'] %>
</p>
<h3><%= raw @text['introduction'] %></h3>
<ol>
  <li>
    <p><%= raw @text['section_1'] %></p>
    <% unless @text['section_1a'].nil? %>
    <ol style="list-style-type: lower-alpha">
      <li><%= raw @text['section_1a'] %></li>
      <li><%= raw @text['section_1b'] %></li>
    </ol>
    <% end %>
  </li>
</ol>
<h3><%= raw @text['rights_granted'] %></h3>
<ol start="2">
  <li>
    <p><%= raw @text['section_2'] %></p>
  </li>
  <li>
    <p><%= raw @text['section_3'] %></p>
    <p><%= raw @text['active_defn_1'] %></p>
    <p><%= raw @text['active_defn_2'] %></p>
    </ul>
  </li>
  <li>
    <p><%= raw @text['section_4'] %></p>
  </li>
  <li>
    <p><%= raw @text['section_5'] %></p>
  </li>
</ol>
<h3><%= raw @text['limitation_of_liability'] %></h3>
<ol start="6">
  <li><p><%= raw @text['section_6'] %></p></li>
  <li><p><%= raw @text['section_7'] %></p></li>
</ol>
<h3><%= raw @text['miscellaneous'] %></h3>
<ol start="8">
  <li>
    <p id="last"><%= raw @text['section_8'] %></p>
  </li>
</ol>

app/views/user/blocked.html.erb
<% content_for :heading do %>
  <h1><%= t 'user.new.heading' %></h1>
<% end %>

<p><%= t 'user.new.no_auto_account_create' %></p>

<p><%= raw t 'user.new.contact_webmaster' %></p>

app/views/user/confirm.html.erb
<% content_for :heading do %>
  <h1><%= t 'user.confirm.heading' %></h1>
  <div class='header-illustration confirm-main'></div>
<% end %>

<% if params[:confirm_string] %>
  <script>
  $("#content").hide();
  </script>

  <p><%= t 'user.confirm.press confirm button' %></p>

  <%= form_tag({}, { :id => "confirm" }) do %>
    <input type="display_name" name="confirm_string" value="<%= params[:display_name] %>">
    <input type="hidden" name="confirm_string" value="<%= params[:confirm_string] %>">
    <input type="submit" name="confirm_action" value="<%= t 'user.confirm.button' %>">
  <% end %>

  <script>
  $("#confirm").submit();
  </script>
<% else %>
  <h1>
    <%= t "user.confirm.introduction_1" %>
    <span class="deemphasize">
      <%= t "user.confirm.introduction_2" %>
    </span>
  </h1>

  <p class='deemphasize'><%= t "user.confirm.reconfirm_html",
                               :reconfirm => url_for(:action => 'confirm_resend')%></p>
<% end %>

app/views/user/list.html.erb
<% @title = t('user.list.title') %>

<% content_for :heading do %>
  <h1><%= t('user.list.heading') %></h1>
<% end %>

<% unless @users.empty? %>
  <%= form_tag do %>
    <%= hidden_field_tag :status, params[:status] if params[:status] %>
    <%= hidden_field_tag :ip, params[:ip] if params[:ip] %>
    <%= hidden_field_tag :page, params[:page] if params[:page] %>
    <table id="user_list">
      <tr>
        <td colspan="2">
          <%= t 'user.list.showing',
              :page => @user_pages.current_page.number,
              :first_item => @user_pages.current_page.first_item,
              :last_item => @user_pages.current_page.last_item,
              :items => @user_pages.item_count,
              :count => @user_pages.current_page.last_item - @user_pages.current_page.first_item + 1
          %>
          <% if @user_pages.page_count > 1 %>
          | <%= raw pagination_links_each(@user_pages, {}) { |n| link_to n, params.merge(:page => n) } %>
          <% end %>
        </td>
        <td>
          <%= check_box_tag "user_all", "1", false %>
        </td>
      </tr>
      <%= render :partial => 'user', :collection => @users %>
    </table>

    <div id="user_list_actions buttons">
      <%= submit_tag t('user.list.confirm'), :name => "confirm" %>
      <%= submit_tag t('user.list.hide'), :name => "hide" %>
    </div>

    <script type="text/javascript">
     $("#user_all").change(function () {
       $("#user_list input[type=checkbox]").prop("checked", $("#user_all").prop("checked"));
     });
    </script>
  <% end %>
<% else %>
  <p><%= t "user.list.empty" %></p>
<% end %>

app/views/user/logout.html.erb
<% content_for :heading do %>
  <h1><%= t 'user.logout.heading' %></h1>
<% end %>

<%= form_tag :action => "logout" do %>
  <%= hidden_field_tag("referer", h(params[:referer])) %>
  <%= hidden_field_tag("session", request.session_options[:id]) %>
  <%= submit_tag t('user.logout.logout_button') %>
<% end %>

app/views/user/no_such_user.html.erb
<% content_for :heading do %>
  <h1><%= t 'user.no_such_user.heading', :user => h(@not_found_user) %></h1>
<% end %>
<p><%= t 'user.no_such_user.body', :user => h(@not_found_user) %></p>

app/views/user/save.html.erb
<%= @user.email %>

app/views/user/view.html.erb
<% content_for :heading do %>
  <div id='userinformation'>
    <%= user_image @this_user %>
    <div class='userinformation-inner'>
      <h1><%= @this_user.display_name %><%= role_icons(@this_user) %></h1>
      <% if @user and @this_user.id == @user.id %>
        <!-- Displaying user's own profile page to themself -->
        <ul class='secondary-actions clearfix'>
          <li>
            <%= link_to t('user.view.my edits'), :controller => 'changeset', :action => 'list', :display_name => @user.display_name %>
            <span class='count-number'><%= number_with_delimiter(@user.changesets.size) %></span>
          </li>
          <li>
            <%= link_to t('user.view.my notes'), :controller => 'notes', :action=> 'mine' %>
          </li>
          <li>
            <%= link_to t('user.view.my traces'), :controller => 'trace', :action=>'mine' %>
            <span class='count-number'><%= number_with_delimiter(@user.traces.size) %></span>
          </li>
          <li>
            <%= link_to t('user.view.my diary'), :controller => 'diary_entry', :action => 'list', :display_name => @user.display_name %>
            <span class='count-number'><%= number_with_delimiter(@user.diary_entries.size) %></span>
          </li>
          <li>
            <%= link_to t('user.view.my comments' ), :controller => 'diary_entry', :action => 'comments', :display_name => @user.display_name %>
          </li>
          <li>
            <%= link_to t('user.view.my settings'), :controller => 'user', :action => 'account', :display_name => @user.display_name %>
          </li>

          <% if @user.blocks.exists? %>
            <li>
              <%= link_to t('user.view.blocks on me'), :controller => 'user_blocks', :action => 'blocks_on', :display_name => @user.display_name %>
              <span class='count-number'><%= number_with_delimiter(@user.blocks.active.size) %></span>
            </li>
          <% end %>

          <% if @user and @user.moderator? and @user.blocks_created.exists? %>
            <li>
              <%= link_to t('user.view.blocks by me'), :controller => 'user_blocks', :action => 'blocks_by', :display_name => @user.display_name %>
              <span class='count-number'><%= number_with_delimiter(@user.blocks_created.active.size) %></span>
            </li>
          <% end %>

        </ul>

        <% else %>
        <!-- Displaying user profile page to the public -->
        <ul class='secondary-actions clearfix'>

          <li>
            <%= link_to t('user.view.edits'), :controller => 'changeset', :action => 'list', :display_name => @this_user.display_name %>
            <span class='count-number'><%= number_with_delimiter(@this_user.changesets.size) %></span>
          </li>
          <li>
            <%= link_to t('user.view.notes'), :controller => 'notes', :action=> 'mine' %>
          </li>
          <li>
            <%= link_to t('user.view.traces'), :controller => 'trace', :action => 'list', :display_name => @this_user.display_name %>
            <span class='count-number'><%= number_with_delimiter(@this_user.traces.size) %></span>
          </li>

          <!-- Displaying another user's profile page -->

          <li>
            <%= link_to t('user.view.send message'), :controller => 'message', :action => 'new', :display_name => @this_user.display_name %>
          </li>
          <li>
            <%= link_to t('user.view.diary'), :controller => 'diary_entry', :action => 'list', :display_name => @this_user.display_name %>
            <span class='count-number'><%= number_with_delimiter(@this_user.diary_entries.size) %></span>
          </li>
          <li>
            <%= link_to t('user.view.comments'), :controller => 'diary_entry', :action => 'comments', :display_name => @this_user.display_name %>
          </li>
          <li>
            <% if @user and @user.is_friends_with?(@this_user) %>
              <%= link_to t('user.view.remove as friend'), remove_friend_path(:display_name => @this_user.display_name), :method => :post %>
            <% elsif @user %>
              <%= link_to t('user.view.add as friend'), make_friend_path(:display_name => @this_user.display_name), :method => :post %>
            <% else %>
              <%= link_to t('user.view.add as friend'), make_friend_path(:display_name => @this_user.display_name) %>
            <% end %>
          </li>

          <% if @this_user.blocks.exists? %>
            <li>
              <%= link_to t('user.view.block_history'), :controller => 'user_blocks', :action => 'blocks_on', :display_name => @this_user.display_name %>
              <span class='count-number'><%= number_with_delimiter(@this_user.blocks.active.size) %></span>
            </li>
          <% end %>

          <% if @this_user.moderator? and @this_user.blocks_created.exists? %>
            <li>
              <%= link_to t('user.view.moderator_history'), :controller => 'user_blocks', :action => 'blocks_by', :display_name => @this_user.display_name %>
              <span class='count-number'><%= number_with_delimiter(@this_user.blocks_created.active.size) %></span>
            </li>
          <% end %>

          <% if @user and @user.moderator? %>
            <li>
            <%= link_to t('user.view.create_block'), :controller => 'user_blocks', :action => 'new', :display_name => @this_user.display_name %>
            </li>
          <% end %>

        </ul>

      <% end %>

      <% if @user and @user.administrator? %>

        <ul class='secondary-actions clearfix'>
          <% if ["active", "confirmed"].include? @this_user.status %>
            <li>
              <%= link_to t('user.view.deactivate_user'), set_status_user_path(:status => 'pending', :display_name => @this_user.display_name), :data => { :confirm => t('user.view.confirm') } %>
            </li>
          <% elsif ["pending"].include? @this_user.status %>
            <li>
              <%= link_to t('user.view.activate_user'), set_status_user_path(:status => 'active', :display_name => @this_user.display_name), :data => { :confirm => t('user.view.confirm') } %>
            </li>
          <% end %>

          <% if ["active", "suspended"].include? @this_user.status %>
            <li>
              <%= link_to t('user.view.confirm_user'), set_status_user_path(:status => 'confirmed', :display_name => @this_user.display_name), :data => { :confirm => t('user.view.confirm') } %>
            </li>
          <% end %>
            <li>
              <% if ["pending", "active", "confirmed", "suspended"].include? @this_user.status %>
                <%= link_to t('user.view.hide_user'), set_status_user_path(:status => 'deleted', :display_name => @this_user.display_name), :data => { :confirm => t('user.view.confirm') } %>
            <% else %>
              <%= link_to t('user.view.unhide_user'), set_status_user_path(:status => 'active', :display_name => @this_user.display_name), :data => { :confirm => t('user.view.confirm') } %>
            </li>
          <% end %>
          <li>
            <%= link_to t('user.view.delete_user'), delete_user_path(:display_name => @this_user.display_name), :data => { :confirm => t('user.view.confirm') } %>
          </li>
        </ul>

        <% end %>

      <p class='deemphasize'>
        <small>
          <%= t 'user.view.mapper since' %> <%= l @this_user.creation_time.to_date, :format => :long %>
          |
          <%= t 'user.view.ct status' %>
          <% if not @this_user.terms_agreed.nil? -%>
          <%= t 'user.view.ct accepted', :ago =>time_ago_in_words(@this_user.terms_agreed)  %>
          <% elsif not @this_user.terms_seen? -%>
          <%= t 'user.view.ct undecided' %>
          <% else -%>
          <%= t 'user.view.ct declined' %>
          <% end -%>
        </small>
      </p>
    </div>

    <div class="user-description richtext"><%= @this_user.description.to_html %></div>

  </div>

  <% if @user and @user.administrator? -%>
    <div class='admin-user-info deemphasize'>
      <small><b><%= t 'user.view.email address' %></b> <%= @this_user.email %></small>
      <% unless @this_user.creation_ip.nil? -%>
        <small><b><%= t 'user.view.created from' %></b> <%= @this_user.creation_ip %></small>
      <% end -%>
      <small><b><%= t 'user.view.status' %></b> <%= @this_user.status.capitalize %></small>
      <small><b><%= t 'user.view.spam score' %></b> <%= @this_user.spam_score %></small>
    </div>
  <% end -%>

<% end %>

  <% if @user and @this_user.id == @user.id %>
    <% if @this_user.home_lat.nil? or @this_user.home_lon.nil? %>
      <div id="map" class="content_map">
        <p id="no_home_location"><%= raw(t 'user.view.if set location', :settings_link => (link_to t('user.view.settings_link_text'), :controller => 'user', :action => 'account', :display_name => @user.display_name)) %></p>
      </div>
    <% else %>
      <% content_for :head do %>
        <%= javascript_include_tag "user" %>
      <% end %>
      <%
        user_data = {
          :lon => @user.home_lon,
          :lat => @user.home_lat,
          :icon => image_path("marker-red.png"),
          :description => render(:partial => "popup", :object => @user, :locals => {:type => "your location"})
        }
      %>
      <%= content_tag "div", "", :id => "map", :class => "content_map", :data => {:user => user_data} %>
    <% end %>

    <% friends = @this_user.friends.collect { |f| f.befriendee } %>
    <% nearby = @this_user.nearby - friends %>

  <div class="activity-block column-1">
    <h3><%= t 'user.view.your friends' %></h3>

    <% if friends.empty? %>
      <%= t 'user.view.no friends' %>
    <% else %>
      <ul class='secondary-actions clearfix'>
        <li><%= link_to t('user.view.friends_changesets'), friend_changesets_path %></li>
        <li><%= link_to t('user.view.friends_diaries'), friend_diaries_path %></li>
      </ul>
      <div id="friends-container">
        <%= render :partial => "contact", :collection => friends, :locals => {:type => "friend"} %>
      </div>
    <% end %>
  </div>

  <div class="activity-block column-1">
    <h3><%= t 'user.view.nearby users' %></h3>

    <% if nearby.empty? %>
      <%= t 'user.view.no nearby users' %>
    <% else %>
      <ul class='secondary-actions clearfix'>
        <li><%= link_to t('user.view.nearby_changesets'), nearby_changesets_path %></li>
        <li><%= link_to t('user.view.nearby_diaries'), nearby_diaries_path %></li>
      </ul>
      <div id="nearbyusers">
        <%= render :partial => "contact", :collection => nearby, :locals => {:type => "nearby mapper"} %>
      </div>
    <% end %>
  </div>
<% end %>